//
// Created by Timothy Shull on 12/6/15.
//

#include "exception_handling.h"
#include <iostream>

/*
void taskmaster() {
    try {
        auto result = do_task();
    } catch (e) {
        std::cout << e << std::endl;
    }
}

int do_task() {
    if () {
        return result;
    } else {
        throw new_error{};
    }
}*/
